# Usage:
#   docker-compose up --force-recreate
#   docker-compose stop
version: '3'

services:
  #--------------#
  teste:
      build: .
      working_dir: /usr
      volumes:
              - ./target:/usr/target
      container_name: api-project-template-multi-cloud_teste
      command: mvn test -Denv=des
